version: "3"

services:
  db:
    image: postgres:11.8-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
  api:
    container_name: desafio-itau-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app/


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.199.1/24
